### PR TITLE
Update the latest dependency and test the function

### PR DESCRIPTION
**Pull request by eligah**

### CODE REVIEW

**Review by saloneerege — COMMENTED** [review]
Can you resolve the go.sum conflict. Remove the existing one in your local repo and update it.

**Review by saloneerege — CHANGES_REQUESTED** [review]
Can you resolve the go.sum conflict. Remove the existing one in your local repo and update it.

**Review by eligah — COMMENTED** [review]
Resolve conflicts

**Review by saloneerege — APPROVED** [review]

**Review by saloneerege — APPROVED** [review]

**Comment by saloneerege** [comment]
Approved. Can be merged.

**Pull request merged**
